# Generated by Django 5.1.3 on 2024-12-18 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Blood Group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Group",
                "verbose_name_plural": "Blood Groups",
            },
        ),
        migrations.CreateModel(
            name="BloodInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("units", models.PositiveIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Date of Birth")),
                (
                    "phone_number",
                    models.CharField(
                        default="0000000000",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("last_donated_date", models.DateField(blank=True, null=True)),
                (
                    "donation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Donation Date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "blood_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blood_bank.bloodgroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Donor",
                "verbose_name_plural": "Donors",
                "ordering": ["-donation_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="0000000000",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(default="Unknown", verbose_name="Address"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Unknown", max_length=100, null=True
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "blood_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blood_bank.bloodgroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("birth_date", models.DateField(verbose_name="Date of Birth")),
                (
                    "contact",
                    models.CharField(max_length=15, verbose_name="Contact Information"),
                ),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("medications", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "nid_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "Enter a valid 10-digit NID number."
                            )
                        ],
                        verbose_name="NID Number",
                    ),
                ),
                (
                    "nid_image",
                    models.ImageField(blank=True, null=True, upload_to="nid_images/"),
                ),
                ("emergency_contact_name", models.CharField(max_length=255)),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                ("consent", models.BooleanField(default=False)),
                ("signature", models.CharField(max_length=255)),
                ("needed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blood_bank.bloodgroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipient",
                "verbose_name_plural": "Recipients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recipient2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("address", models.TextField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=15, null=True)),
                ("nid_number", models.CharField(blank=True, max_length=20, null=True)),
                ("by_date", models.DateField(blank=True, null=True)),
                (
                    "blood_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blood_bank.bloodgroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
