# Generated by Django 5.1.3 on 2024-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0002_alter_bloodinventory_blood_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipient2",
            name="user",
        ),
        migrations.AddField(
            model_name="recipient2",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipient2",
            name="birth_date",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="recipient2",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
    ]
