# Generated by Django 5.1.3 on 2024-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0004_donor2"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("health_confirmed", models.BooleanField()),
                ("emergency_donor", models.BooleanField(default=False)),
                ("preferred_times", models.TextField()),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Donor Registration",
                "verbose_name_plural": "Donor Registrations",
            },
        ),
        migrations.DeleteModel(
            name="Donor2",
        ),
    ]
