# Generated by Django 5.1.3 on 2024-12-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0005_donorreg_delete_donor2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donorreg",
            options={},
        ),
        migrations.AlterField(
            model_name="donorreg",
            name="health_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="donorreg",
            name="preferred_times",
            field=models.TextField(blank=True, null=True),
        ),
    ]
