# Generated by Django 5.1.3 on 2024-12-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0006_alter_donorreg_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donorreg",
            name="last_donation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last Donation Date"
            ),
        ),
    ]
