# Generated by Django 5.1.3 on 2024-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0008_donorreg_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient2",
            name="units",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
